sudo: false

language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO=1.8.18
  - DJANGO=1.10.7
  - DJANGO=1.11

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=1.10.7
    - python: "3.3"
      env: DJANGO=1.11
    - python: "3.6"
      env: DJANGO=1.8.18
    - python: "3.6"
      env: DJANGO=1.10.7

install:
  - pip install -U Django==$DJANGO
  - pip install -Ur requirements-test.txt

script:
  - coverage run --rcfile=.coveragerc `which py.test` -v --pep8

after_success:
  - coverage report -m
  - coveralls
