sudo: false

language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - DJANGO=1.4.22
  - DJANGO=1.5.12
  - DJANGO=1.6.11
  - DJANGO=1.7.11
  - DJANGO=1.8.15
  - DJANGO=1.9.10
  - DJANGO=1.10.2

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=1.7.11
    - python: "2.6"
      env: DJANGO=1.8.15
    - python: "2.6"
      env: DJANGO=1.9.10
    - python: "2.6"
      env: DJANGO=1.10.2
    - python: "3.3"
      env: DJANGO=1.4.22
    - python: "3.3"
      env: DJANGO=1.9.10
    - python: "3.3"
      env: DJANGO=1.10.2
    - python: "3.4"
      env: DJANGO=1.4.22
    - python: "3.5"
      env: DJANGO=1.4.22
    - python: "3.5"
      env: DJANGO=1.5.12
    - python: "3.5"
      env: DJANGO=1.6.11
    - python: "3.5"
      env: DJANGO=1.7.11

install:
  - pip install -U Django==$DJANGO
  - pip install -Ur requirements-test.txt

script:
  - coverage run --rcfile=.coveragerc `which py.test` -v --pep8

after_success:
  - coverage report -m
  - coveralls
